import imageDog1 from "../../assets/images/dog1.svg";

export const animals = [
  {
    id: 1,
    image: imageDog1,
    name: "Julia",
    gender: "Fêmea",
    breed: "Sem Raça Definida",
    age: "3 anos",
  },
  {
    id: 2,
    image: imageDog1,
    name: "Max",
    gender: "Macho",
    breed: "Sem Raça Definida",
    age: "2 anos",
  },
  {
    id: 3,
    image: imageDog1,
    name: "Bella",
    gender: "Fêmea",
    breed: "Sem Raça Definida",
    age: "4 anos",
  },
  {
    id: 4,
    image: imageDog1,
    name: "Billy",
    gender: "Fêmea",
    breed: "Sem Raça Definida",
    age: "3 anos",
  },
  {
    id: 5,
    image: imageDog1,
    name: "Pipoca",
    gender: "Macho",
    breed: "Sem Raça Definida",
    age: "2 anos",
  },
  {
    id: 6,
    image: imageDog1,
    name: "Costelinha",
    gender: "Fêmea",
    breed: "Sem Raça Definida",
    age: "4 anos",
  },
  {
    id: 7,
    image: imageDog1,
    name: "Coragem",
    gender: "Macho",
    breed: "Sem Raça Definida",
    age: "2 anos",
  },
  {
    id: 8,
    image: imageDog1,
    name: "Snoop",
    gender: "Fêmea",
    breed: "Sem Raça Definida",
    age: "4 anos",
  },
  {
    id: 9,
    image: imageDog1,
    name: "Scooby Doo",
    gender: "Fêmea",
    breed: "Sem Raça Definida",
    age: "4 anos",
  },
];
